# Generated by Django 4.0.5 on 2022-06-09 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projeto',
            options={},
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='created_at',
        ),
    ]
