# Generated by Django 4.0.4 on 2022-06-06 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('ocupacao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Imagens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(help_text='Procure as imagens', null=True, upload_to='media/')),
                ('voluntario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sobre.voluntario')),
            ],
        ),
    ]
