# Generated by Django 4.0.4 on 2022-06-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sobre', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voluntario',
            name='imagem',
            field=models.ImageField(default=1, upload_to='voluntarios'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Imagens',
        ),
    ]
