# Generated by Django 4.0.4 on 2022-06-01 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(help_text='Procure as imagens)', upload_to='media/')),
                ('post', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
            ],
        ),
    ]
