# Generated by Django 4.0.5 on 2022-06-06 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_imagens'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parceiros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(help_text='Procure as imagens', null=True, upload_to='media/')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.AlterField(
            model_name='imagens',
            name='img',
            field=models.ImageField(help_text='Procure as imagens', null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='post',
            name='logo',
            field=models.ManyToManyField(help_text='Selecione uma ou mais empresas parceiras', to='blog.parceiros'),
        ),
    ]
